### ISSUE TITLE
Incorporating JS chart libraries (e.g., Highcharts, Chart.js, etc.)

### ISSUE THREAD

**Issue by wenstarner** [martinlaukkanen/report-pcf#1]
Hi, this looks great! And I've been looking for a way to extend the native charting experience in forms for a long time.

Would it be possible to incorporate Highcharts or Chart.js in this PCF component? So that there's a wider range of visualisations and a common 'standard' for people to use.

Sorry if this is a silly question!

**Comment by martinlaukkanen** [comment]
Hey, yes definitely my plan was to add other chart libraries to this in the future. For now I started with one I know well but I have a few others that I've been playing with.
I tried to build the component to be modular so that dropping in another chart / lib is easy.

**Comment by wenstarner** [comment]
Great to hear! Thank you so much for your reply. I think it is one of the best PCF components I've seen in a while!
